### PR TITLE
unzip have to be installed

### PR DESCRIPTION
**Pull request by 000xxx**

### CODE REVIEW

**Comment by ispysoftware** [comment]
it is installed earlier as part of the ffmpeg build - although perhaps not if you say no to it.
Needs to detect the platform anyway so i'll close this and update it

**Comment by 000xxx** [comment]
ffmpeg is preinstalled on Ubuntu 22.10 but no unzip. So user don't need to build ffmpeg but not possible to unpack Agent DVR zip.

**Comment by ispysoftware** [comment]
ah ok - is it ffmpeg v5? does it work?

**Comment by 000xxx** [comment]
Yep, it works!

```
zer0@pi4:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
zer0@pi4:~$ ffmpeg -v
ffmpeg version 5.1.1-1ubuntu2.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.2.0-3ubuntu1)
```

**Pull request closed without merging**
